-- ============================================================
-- Views for Transport & Logistics Management Database
-- Author: Alian Villa Ochoa
-- ============================================================

---------------------------------------------------------------
-- 1. View: Customer Revenue Summary
--    Total revenue generated by each customer
---------------------------------------------------------------
CREATE OR REPLACE VIEW vw_customer_revenue AS
SELECT 
    c.id AS customer_id,
    c.name AS customer_name,
    SUM(i.amount) AS total_revenue,
    COUNT(i.id) AS invoice_count
FROM customers c
JOIN shipment_customers sc ON c.id = sc.customer_id
JOIN invoices i ON sc.shipment_id = i.shipment_id
GROUP BY c.id, c.name;

---------------------------------------------------------------
-- 2. View: Driver Performance Summary
--    Average delivery time and total shipments per driver
---------------------------------------------------------------
CREATE OR REPLACE VIEW vw_driver_performance AS
SELECT 
    d.id AS driver_id,
    d.name AS driver_name,
    COUNT(sd.shipment_id) AS total_shipments,
    AVG(EXTRACT(EPOCH FROM (s.delivery_date - s.shipment_date)) / 3600) AS avg_delivery_hours
FROM drivers d
JOIN shipment_drivers sd ON d.id = sd.driver_id
JOIN shipments s ON sd.shipment_id = s.id
WHERE s.delivery_date IS NOT NULL
GROUP BY d.id, d.name;

---------------------------------------------------------------
-- 3. View: Vehicle Utilization Summary
--    Shipments per vehicle and total revenue generated
---------------------------------------------------------------
CREATE OR REPLACE VIEW vw_vehicle_utilization AS
SELECT 
    v.id AS vehicle_id,
    v.plate_number,
    COUNT(s.id) AS total_shipments,
    SUM(i.amount) AS total_revenue
FROM vehicles v
LEFT JOIN shipments s ON v.id = s.vehicle_id
LEFT JOIN invoices i ON s.id = i.shipment_id
GROUP BY v.id, v.plate_number;

---------------------------------------------------------------
-- 4. View: Route Delivery Performance
--    Average delivery time and total shipments per route
---------------------------------------------------------------
CREATE OR REPLACE VIEW vw_route_performance AS
SELECT 
    r.id AS route_id,
    r.origin,
    r.destination,
    COUNT(s.id) AS total_shipments,
    AVG(EXTRACT(EPOCH FROM (s.delivery_date - s.shipment_date)) / 3600) AS avg_delivery_hours
FROM routes r
JOIN shipments s ON r.id = s.route_id
WHERE s.delivery_date IS NOT NULL
GROUP BY r.id, r.origin, r.destination;

---------------------------------------------------------------
-- 5. View: Shipment Revenue Summary
--    Total revenue and invoice count per shipment
---------------------------------------------------------------
CREATE OR REPLACE VIEW vw_shipment_revenue AS
SELECT 
    s.id AS shipment_id,
    COUNT(i.id) AS invoice_count,
    SUM(i.amount) AS total_revenue,
    s.status,
    s.shipment_date,
    s.delivery_date
FROM shipments s
LEFT JOIN invoices i ON s.id = i.shipment_id
GROUP BY s.id, s.status, s.shipment_date, s.delivery_date;

---------------------------------------------------------------
-- 6. View: Overdue Invoices
--    All invoices past due date
---------------------------------------------------------------
CREATE OR REPLACE VIEW vw_overdue_invoices AS
SELECT 
    i.id AS invoice_id,
    i.shipment_id,
    i.amount,
    i.issued_date,
    i.due_date,
    i.status
FROM invoices i
WHERE i.status = 'Overdue';

---------------------------------------------------------------
-- 7. View: Shipments With Multiple Customers
---------------------------------------------------------------
CREATE OR REPLACE VIEW vw_multi_customer_shipments AS
SELECT 
    s.id AS shipment_id,
    COUNT(sc.customer_id) AS customer_count
FROM shipments s
JOIN shipment_customers sc ON s.id = sc.shipment_id
GROUP BY s.id
HAVING COUNT(sc.customer_id) > 1;

---------------------------------------------------------------
-- 8. View: Shipments With Multiple Drivers
---------------------------------------------------------------
CREATE OR REPLACE VIEW vw_multi_driver_shipments AS
SELECT 
    s.id AS shipment_id,
    COUNT(sd.driver_id) AS driver_count
FROM shipments s
JOIN shipment_drivers sd ON s.id = sd.shipment_id
GROUP BY s.id
HAVING COUNT(sd.driver_id) > 1;

---------------------------------------------------------------
-- 9. View: Customer Shipment Count
---------------------------------------------------------------
CREATE OR REPLACE VIEW vw_customer_shipment_count AS
SELECT 
    c.id AS customer_id,
    c.name AS customer_name,
    COUNT(sc.shipment_id) AS total_shipments
FROM customers c
JOIN shipment_customers sc ON c.id = sc.customer_id
GROUP BY c.id, c.name;

---------------------------------------------------------------
-- 10. View: Driver Revenue Summary
---------------------------------------------------------------
CREATE OR REPLACE VIEW vw_driver_revenue AS
SELECT 
    d.id AS driver_id,
    d.name AS driver_name,
    SUM(i.amount) AS total_revenue
FROM drivers d
JOIN shipment_drivers sd ON d.id = sd.driver_id
JOIN invoices i ON sd.shipment_id = i.shipment_id
GROUP BY d.id, d.name;
